language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bebop' ]; then cd .. && eval "mv $currentfolder generator-bebop" && cd generator-bebop; fi

